apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: demo-node
    name: demo-node
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: demo-node
    spec:
      containers:
      - image: nj93/hello-node
        name: demo-node
        ports:
        - containerPort: 8000
        resources: 
         requests: 
          cpu: 100m
          memory: 100Mi
         limits: 
          cpu: 100m
          memory: 100Mi
